# Generated by Django 5.0.1 on 2024-01-16 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('LODGING', 'Lodging'), ('FOOD', 'Food'), ('BILL', 'Bill'), ('TRANSPORTATION', 'Transportation'), ('ENTERTAINMENT', 'Entertainment')], default='Lodging', max_length=15)),
                ('description', models.TextField(default='N/A', max_length=250)),
                ('amount', models.PositiveIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.group')),
            ],
        ),
    ]
