# Generated by Django 5.0.1 on 2024-01-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_expenses_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(default='N/A', max_length=250),
        ),
    ]
